import { REFERENCES } from "./parameters";
/**
 * Independent literature constraints. These are intentionally kept separate
 * from the theoretical curves: they are not samples generated by this app and
 * they are not fitted at runtime.
 */
export interface ObservationPoint {
  radiusKpc: number;
  velocityKmS: number;
  uncertaintyKmS: number;
  radiusUncertaintyKpc?: number;
  source: (typeof REFERENCES)[keyof typeof REFERENCES];
  note: string;
}

export const OBSERVATIONS: ObservationPoint[] = [
  {
    radiusKpc: 8.122,
    velocityKmS: 229.0,
    uncertaintyKmS: 0.2,
    source: REFERENCES.eilers,
    note: "Eilers: erro estatístico; sistemáticos estimados de 2–5% não incluídos.",
  },
  {
    radiusKpc: 8.15,
    radiusUncertaintyKpc: 0.15,
    velocityKmS: 236,
    uncertaintyKmS: 7,
    source: REFERENCES.reid,
    note: "Reid: masers; parâmetros ajustados conjuntamente.",
  },
];
